spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 822a5d91a6e9fb920cbf7ae96634c26ffc0cd7b144b53cd7a98943a40f87f3a2
            client-secret: 19f99ae7de4336926ffadf47ed82c0edcee50ba44a6175683717750e543342fb
            client-name: Gitee
            provider: gitee
            redirect-uri: "{baseUrl}/login/oauth2/code/gitee"
            authorization-grant-type: authorization_code
            scope: user_info
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: login
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp148z5e593e5u63nvo.mysql.rds.aliyuncs.com:3306/openSourceTest?serverTimezone=UTC
    username: root
    password: Admin!@#