mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.sdu.open.source.site.entity
  config-location: classpath:mybatis-config.xml
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp15i4z510c996b2llo.mysql.rds.aliyuncs.com:3306/openSourceSite?serverTimezone=UTC
    username: ericsalvatore
    password: DHJ#20152011#dhj
