mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.sdu.open.source.site.entity
  config-location: classpath:mybatis-config.xml

server:
  port: 8080

spring:
  mail:
    username: cislc210sdu@163.com
    password: TTid83v3vnt7sWSi
    host: smtp.163.com
    # 端口号465或587
    port: 465
    protocol: smtps
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式
          debug: true
          ssl: true
